config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#home', as: 'root'

  get '/about', to: 'welcome#about', as: "about_page"
  get '/login', to: 'sessions#new', as: "login"
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # resources :login_details
  resources :families
  resources :people

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :family_people
  has_many :people, through: :family_people

end

app/models/family_person.rb
class FamilyPerson < ApplicationRecord
  belongs_to :person
  belongs_to :family

  enum role: ["caregivers", "children", "sitters", "friends"]
end

app/models/login_detail.rb
class LoginDetail < ApplicationRecord
  has_secure_password
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  has_secure_password
  has_many :family_people
  has_many :families, through: :family_people
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery with: :exception

  def index
  end

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end

  # GET /families/1
  # GET /families/1.json
  def show
    
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.fetch(:family, {})
    end
end

app/controllers/login_details_controller.rb
class LoginDetailsController < ApplicationController
  before_action :set_login_detail, only: [:show, :edit, :update, :destroy]

  # GET /login_details
  # GET /login_details.json
  def index
    @login_details = LoginDetail.all
  end

  # GET /login_details/1
  # GET /login_details/1.json
  def show
  end

  # GET /login_details/new
  def new
    @login_detail = LoginDetail.new
  end

  # GET /login_details/1/edit
  def edit
  end

  # POST /login_details
  # POST /login_details.json
  def create
    @login_detail = LoginDetail.new(login_detail_params)

    respond_to do |format|
      if @login_detail.save
        format.html { redirect_to @login_detail, notice: 'Login detail was successfully created.' }
        format.json { render :show, status: :created, location: @login_detail }
      else
        format.html { render :new }
        format.json { render json: @login_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /login_details/1
  # PATCH/PUT /login_details/1.json
  def update
    respond_to do |format|
      if @login_detail.update(login_detail_params)
        format.html { redirect_to @login_detail, notice: 'Login detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @login_detail }
      else
        format.html { render :edit }
        format.json { render json: @login_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /login_details/1
  # DELETE /login_details/1.json
  def destroy
    @login_detail.destroy
    respond_to do |format|
      format.html { redirect_to login_details_url, notice: 'Login detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login_detail
      @login_detail = LoginDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_detail_params
      params.require(:login_detail).permit(:user_name, :password, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @families = @person.families

    if !current_user
      redirect_to root_path
    end

  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find_by(params[:person_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email, :phone_number, :city)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @person = Person.new
  end

  def create
    user_params = params.require(:person).permit(:email, :password)

    @person = Person.confirm(user_params)
    if @person
      login(@person)
      flash[:notice] = "Successfully logged in as #{@person.first_name}!"
      redirect_to '/people/' + @person.person_id
    else
      puts 'error'
      flash[:error] = "User Name and Password do not match"
      redirect_to login_path
    end
  end

  def destroy
    logout
    flash[:notice]= "Successfully logged out."
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
		if current_user
			@person = current_user
		end
		@person = Person.new
	end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/login_details_helper.rb
module LoginDetailsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(person)
    session[:person_id] = person
    @current_user = person
  end

  def current_user
    @current_user ||= Person.find_by_id(session[:person_id])
  end

  def logout
    @current_user = session[:person_id] = nil
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/families/_form.html.erb
<%= form_for(family) do |f| %>
  <% if family.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
      <% family.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="new-family-form">
    <%= semantic_form_for @person do |f| %>
      <%= f.inputs do %>
        <%= f.input :family_name %>
      <% end %>
      <%= f.actions %>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
      </div>
    <% end %>

  <div class="form-group row">
    <label for="example-search-input" class="col-xs-2 col-form-label">Search</label>
    <div class="col-xs-10">
      <input class="form-control" type="search" value="How do I shoot web" id="example-search-input">
    </div>
  </div>
  <div id="find-a-family">
    <%= semantic_form_for @person do |f| %>
      <%= f.inputs do %>
        <%= f.input :family_name %>
      <% end %>
      <%= f.actions %>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
      </div>
    <% end %>

app/views/families/edit.html.erb
<h1>Editing Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Show', @family %> |
<%= link_to 'Back', families_path %>

app/views/families/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Families</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @families.each do |family| %>
      <tr>
        <td><%= link_to 'Show', family %></td>
        <td><%= link_to 'Edit', edit_family_path(family) %></td>
        <td><%= link_to 'Destroy', family, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Family', new_family_path %>

app/views/families/new.html.erb
<h1>Add a Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', person_path(@person) %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_family_path(@family) %> |
<%= link_to 'Back', families_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SitterSwapNewModels</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body lang = "en">
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/login_details/_form.html.erb
<%= form_for(login_detail) do |f| %>
  <% if login_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(login_detail.errors.count, "error") %> prohibited this login_detail from being saved:</h2>

      <ul>
      <% login_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions" id="create-login-button">
    <%= f.submit %>
  </div>
<% end %>

app/views/login_details/edit.html.erb
<h1>Editing Login Detail</h1>

<%= render 'form', login_detail: @login_detail %>

<%= link_to 'Show', @login_detail %> |
<%= link_to 'Back', login_details_path %>

app/views/login_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Log In To SitterSwap</h1>


<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Password</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @login_details.each do |login_detail| %>
      <tr>
        <td><%= login_detail.user_name %></td>
        <td><%= login_detail.password %></td>
        <td><%= login_detail.person %></td>
        <td><%= link_to 'Show', login_detail %></td>
        <td><%= link_to 'Edit', edit_login_detail_path(login_detail) %></td>
        <td><%= link_to 'Destroy', login_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login Detail', new_login_detail_path %>

app/views/login_details/new.html.erb
<h1>New Login Detail</h1>

<%= render 'form', login_detail: @login_detail %>

<%= link_to 'Back', login_details_path %>

app/views/login_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @login_detail.user_name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login_detail.password %>
</p>

<p>
  <strong>Person:</strong>
  <%= @login_detail.person %>
</p>

<%= link_to 'Edit', edit_login_detail_path(@login_detail) %> |
<%= link_to 'Back', login_details_path %>

app/views/people/_families.html.haml
#family_list{:title => "my families"}
  -@families.each do |f|
    .family
      .name
        f.family_name

app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/_friends.html.haml
#friend_list{:title => "my friends"}
  -@families.each do |f|
    .friend
      .name
        f.friend_name

app/views/people/_sitters.html.haml
#sitter_list{:title => "my sitters"}
  -@families.each do |f|
    .sitter
      .first_name
      .last_name

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.email %></td>
        <td><%= person.phone_number %></td>
        <td><%= person.city %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= semantic_form_for @person do |f| %>
  <%= f.inputs do %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :phone_number %>
    <%= f.input :city %>
    <%= f.input :email %>
    <%= f.input :password %>
  <% end %>
  <%= f.actions %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<!-- if !current_user -->
<!-- <h1>You need to make a login!</h1>
<%= link_to 'Create Login', new_login_detail_url %> -->

<h1>Your Profile Details</h1>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @person.phone_number %>
</p>

<p>
  <strong>City:</strong>
  <%= @person.city %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Delete Profile', person_path(@person) %> |
<%= link_to 'Back', people_path %>

<!-- if role is caregiver, show one family -->
<h2>Your Family</h2>
<%= link_to 'Add Family', families_path(@person) %> |
<%= render "families" %>

<!-- if role is sitter, show all families -->
<h2>Your Families</h2>
<%= link_to 'Add Family', families_path(@person) %> |
<%= render "families" %>

<!-- if role is caregiver, show all sitters -->
<h2>Your Sitters</h2>
<%= render "sitters" %>

app/views/welcome/about.html.erb
<h1>This is the about page</h1>

app/views/welcome/home.html.erb
<h1>This is our home/index page</h1>